version: "3"

services:
  hermes:
    build:
      dockerfile: docker/debug-hermes.dockerfile
      context: ./
    ports:
      - 8000:8000
      - 9000:9000
      - 10000:10000
      - 2345:2345
    command: "--listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout,rpc --accept-multiclient --api-version=2 exec ./hermes -j localhost:9000"
